openapi: 3.0.1
info:
  title: Northwind Modulith API
  description: Northwind Modulith API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Local Server

tags:
  - name: Product
    description: Performs CRUD operations for products
  - name: Order
    description: Performs CRUD operations for orders
  - name: Supplier
    description: Performs CRUD operations for suppliers
  - name: Customer
    description: Performs CRUD operations for customers

paths:
  /products:
    get:
      summary: Returns a list of products
      description: Returns a list of products
      operationId: getProducts
      tags:
        - Product
      parameters:
        - name: productKey
          in: query
          description: Key for the product
          required: false
          schema:
            type: string
        - name: searchOrderName
          in: query
          description: Filter products by their titles or partial match
          required: false
          schema:
            type: string
        # - name: supplierId
        #   in: query
        #   description: Filter products by supplier id
        #   required: false
        #   schema:
        #     type: integer
        #     format: int32
        # - name: categoryId
        #   in: query
        #   description: Filter products by category id
        #   required: false
        #   schema:
        #     type: integer
        #     format: int32
        # - name: minPrice
        #   in: query
        #   description: Filter products by minimum price
        #   required: false
        #   schema:
        #     type: number
        #     format: float
        # - name: maxPrice
        #   in: query
        #   description: Filter products by maximum price
        #   required: false
        #   schema:
        #     type: number
        #     format: float
        # - name: page
        #   in: query
        #   description: Pagination
        #   required: false
        #   schema:
        #     type: integer
        #     format: int32
        # - name: limit #todo externalise this part
        #   in: query
        #   description: Page
        #   required: false
        #   schema:
        #     type: integer
        #     format: int32
        #     default: 12
        # - name: sort
        #   in: query
        #   description: Sort by this field
        #   required: false
        #   schema:
        #     type: string
        #     enum: [name, price, supplier, category]
        #     default: name
        # - name: direction
        #   in: query
        #   description: Sorting direction
        #   required: false
        #   schema:
        #     type: string
        #     enum: [asc, desc]
        #     default: asc
      responses:
        '200':
          description: List of matching product results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    # post:
    #   summary: Add a product to the database
    #   description: Add a product to the database
    #   operationId: addProduct
    #   tags:
    #     - Product
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Product'
    #       application/xml:
    #         schema:
    #           $ref: '#/components/schemas/Product'
    #   responses:
    #     '201':
    #       description: Product added
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Product' #todo change to surigate key
    #         application/xml:
    #           schema:
    #             $ref: '#/components/schemas/Product'

  /orders:
    get:
      summary: Returns a list of orders
      description: Returns a list of orders
      operationId: getOrders
      tags:
        - Order
      parameters:
        - name: orderKey
          in: query
          description: Key for the order
          required: false
          schema:
            type: string
        - name: customerKey
          in: query
          description: Filter orders by customer
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of matching order results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /suppliers:
    get:
      summary: Returns a list of suppliers
      description: Returns a list of suppliers
      operationId: getSuppliers
      tags:
        - Supplier
      parameters:
        - name: supplierKey
          in: query
          description: Key for the supplier
          required: false
          schema:
            type: string
        - name: searchSupplierName
          in: query
          description: Search for a supplier by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of matching supplier results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'


  /customer:
    get:
      summary: Returns a list of customers
      description: Returns a list of customers
      operationId: getCustomers
      tags:
        - Customer
      parameters:
        - name: customerKey
          in: query
          description: Key for the customer
          required: false
          schema:
            type: string
        - name: searchCustomerName
          in: query
          description: Search for a customer by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of matching customer results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'



  # /categories:
  #   get:
  #     summary: Returns a list of categories
  #     description: Returns a list of categories
  #     operationId: getCategories
  #     tags:
  #       - Category
  #     parameters:
  #       - name: categoryId
  #         in: query
  #         description: Filter products by categoryId
  #         required: false
  #         schema:
  #           type: string
  #       - name: categoryName
  #         in: query
  #         description: Filter products by categoryName
  #         required: false
  #         schema:
  #           type: string

  #       - name: limit #todo externalise this part
  #         in: query
  #         description: Page
  #         required: false
  #         schema:
  #           type: integer
  #           format: int32
  #           default: 12
  #       - name: sort
  #         in: query
  #         description: Sort by this field
  #         required: false
  #         schema:
  #           type: string
  #           enum: [name, price, supplier, category]
  #           default: name
  #       - name: direction
  #         in: query
  #         description: Sorting direction
  #         required: false
  #         schema:
  #           type: string
  #           enum: [asc, desc]
  #           default: asc
  #     responses:
  #       '200':
  #         description:
  #           List of matching category results
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Category'
  #           application/xml:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Category'



components:
  schemas:

    Product:
      type: object
      properties:
        productKey:
          type: string
          example: 'PRD-001'
        name:
          type: string
          example: 'Blink Notepad'
        description:
          type: string
          example: 'Large notepad'
        supplierId:
          type: integer
          format: int32
          example: 'todo make into own object'
        category:
          $ref: '#/components/schemas/Category'
          # type: integer
          # format: int32
        unit:
          type: string
          example: 'Pack of five'
        price:
          type: number
          format: float
          example: '10'

    Order:
      type: object
      properties:
        orderKey:
          type: string
          example: 'ORD-001'
        orderDate:
          type: string
          format: date-time
        shipmentId:
          type: string
        orderDetails:
          type: array
          items:
            $ref: '#/components/schemas/OrderDetail'

    OrderDetail:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer

    Supplier:
      type: object
      properties:
        supplierKey:
          type: string
          example: 'SUP-001'
        supplierName:
          type: string
          example: 'Sporting Supplier store'
        addressDetails:
          $ref: '#/components/schemas/AddressDetails'
        #   type: string
        #   example: '1 Queen Street'
        # city:
        #   type: string
        #   example: 'Auckland'
        # postalCode:
        #   type: string
        #   example: '1060'
        # country:
        #   type: string
        #   example: 'New Zealand'
        phone:
          type: string
          example: '0912345678'

    Customer:
      # Can I reuse an address as its own type?
      type: object
      properties:
        customerKey:
          type: string
          example: 'CUST-001'
        customerName:
          type: string
          example: 'My mowing business'
        addressDetails:
          $ref: '#/components/schemas/AddressDetails'

    AddressDetails:
      type: object
      properties:
        address:
          type: string
          example: '1 Queen Street'
        city:
          type: string
          example: 'Auckland'
        postalCode:
          type: string
          example: '1060'
        country:
          type: string
          example: 'New Zealand'



    Category:
      type: object
      properties:
        categoryId:
          type: integer
          format: int32
        categoryName:
          type: string
        description:
          type: string




    # /products/{id}:

    # /orders:

    # /orders/{id}:

  # /shippers:

  # /shippers/{id}:

  # /employees:

  # /employees/{id}:

  # /customer

  # /customer/{id}: